name: Upload Artifact

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build and upload boot.3dsx
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm
      options: --user 1001

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build
        run: make -j$(nproc --all)

      - name: Upload boot.3dsx
        uses: actions/upload-artifact@v4
        with:
          name: boot-3dsx
          path: boot.3dsx
